//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;

public class NetflixPlayer : IPlayer
{
	public virtual void PlayMovie(object movieName)
	{
        Debug.WriteLine("Välkommen till Netflix, kolla på film vart du vill!");
	}

}

